# Add local bin directory to path
export PATH=$PATH:~/.local/bin
export EDITOR=nvim

# Set the directory we want to store zinit and plugins
ZINIT_HOME="${HOME}/.local/share/zinit/zinit.git"

# Download Zinit, if it's not there yet
if [ ! -d "$ZINIT_HOME" ]; then
    mkdir -p "$(dirname "$ZINIT_HOME")" && \
    git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME" || \
    { echo "Error: Failed to install zinit" >&2; return 1; }
fi

# Source/Load zinit
source "${ZINIT_HOME}/zinit.zsh"

# Add in zsh plugins
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light Aloxaf/fzf-tab
zinit light zsh-users/zsh-syntax-highlighting

# Load completions
autoload -Uz compinit
if [[ -n ~/.zcompdump(#qN.mh+24) ]]; then
    compinit
else
    compinit -C
fi
zinit cdreplay -q

# Configure prompt
eval "$(oh-my-posh init zsh --config ~/GIT/dotfiles/zsh/tokyonight_storm.omp.json)"

# Keybindings
bindkey -v
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward
bindkey '^f' autosuggest-accept
# Fix backward key after entering insert mode after normal mode
bindkey '^?' backward-delete-char

#Open fuzzy find
bindkey -s '^g' 'tv git-repos --layout portrait\n'

# History
HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups

# Yank to the system clipboard
function vi-yank-system {
    zle vi-yank
    printf '%s' "$CUTBUFFER" | pbcopy
}

zle -N vi-yank-system
bindkey -M vicmd 'y' vi-yank-system

# Allow with C-x to edit the current command in a vim buffer
autoload -Uz edit-command-line
zle -N edit-command-line edit-command-line
bindkey '^x' edit-command-line

# Completion styling
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'

# Aliases
alias ls='ls --color'
alias q='pi -p --model us.anthropic.claude-sonnet-4-6'

# Shell integrations
eval "$(fzf --zsh)"
eval "$(zoxide init zsh)"
